---
- name: nginx config verification
  command: nginx -t
  changed_when: false
  become: yes
  notify: reload nginx configuration

- name: reload nginx configuration
  service:
    name: nginx
    state: reloaded
  become: yes