---
###### nginx installation ######
- name: Ensure nginx is installed
  yum:
    name: nginx
    state: latest
  become: yes

- name: Configure nginx service to start at boot and actually start the service
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes

- name: Ensure reverse proxy main configuration is deployed 
  copy:
    src: 'nginx.conf'
    dest: '/etc/nginx/nginx.conf'
    mode: 0644
  register: triger_nginx_config_verification

- name: Ensure reverse proxy Feature-Specific Configuration Files are deployed 
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - {src: http.j2, dest: '/etc/nginx/conf.d/http'}
    - {src: redirect.j2, dest: '/etc/nginx/conf.d/redirect'}
  register: triger_nginx_config_verification

- name: Verify nginx config
  command: nginx -t
  changed_when: false
  become: yes
  when: triger_nginx_config_verification.changed
  notify: reload nginx configuration