---
###### nginx installation ######
- name: Ensure nginx is installed
  yum:
    name: nginx
    state: latest

- name: Configure nginx service to start at boot and actually start the service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure reverse proxy configuration template is deployed 
  template:
    src: 'nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    mode: 0644
  notify: restart nginx service